version: '3.9'

services:


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_EXT://localhost:29092,LISTENER_INT://kafka:9092
      - KAFKA_LISTENERS=LISTENER_INT://0.0.0.0:9092,LISTENER_EXT://0.0.0.0:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:1
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR:1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR:1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR:1
      - KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS:1
  kafka-2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "39092:39092"
    environment:
      - KAFKA_BROKER_ID:2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_EXT://localhost:39092,LISTENER_INT://kafka-2:9092
      - KAFKA_LISTENERS=LISTENER_INT://0.0.0.0:9092,LISTENER_EXT://0.0.0.0:39092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:1
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR:1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR:1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR:1
      - KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS:1

  kafka-3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "49092:49092"
    environment:
      - KAFKA_BROKER_ID:3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_EXT://localhost:49092,LISTENER_INT://kafka-3:9092
      - KAFKA_LISTENERS=LISTENER_INT://0.0.0.0:9092,LISTENER_EXT://0.0.0.0:49092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:1
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR:1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR:1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR:1
      - KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS:1

  connect:
    image: debezium/connect
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - zookeeper
      - kafka
